Update Github link
kinowashere/manueru.com pull request #1
Opened 2021-06-07 08:46 UTC by voukau

2021-06-07 15:56 UTC, kinowashere requested changes
**QA Failed**

**Description** - eetkino appears as the text instead of kinowashere

**Expected** - kinowashere appears as the link's text and directs you to kinowashere's GitHub

**Steps to Repoduce**

1. Open `public/index.html`

2021-06-07 15:56 UTC, kinowashere commented on public/index.html
> +        <h4>GitHub > <a href="https://github.com/kinowashere">eetkino</a></h4>
There's unexpected behavior here.

2021-06-07 18:11 UTC, voukau commented on public/index.html
> +        <h4>GitHub > <a href="https://github.com/kinowashere">eetkino</a></h4>
Investigating.

2021-06-08 17:48 UTC, kinowashere approved these changes
**QA Passed**

Great job! Looks good.

2021-06-08 17:48 UTC, kinowashere commented on public/index.html
> +        <h4>GitHub > <a href="https://github.com/kinowashere">kinowashere</a></h4>
Yup looks good

2021-06-08 17:48 UTC, merged